import CustomsDutyEstimateV1SchemaJson from "../schemas/duty-estimate.v1.schema.json" with { type: "json" };
import CustomsRulesetContainerV1SchemaJson from "../schemas/customs-ruleset-container.v1.schema.json" with { type: "json" };
import CustomsRulesetV1SchemaJson from "../schemas/customs-ruleset.v1.schema.json" with { type: "json" };
import Schedule1ParseResultV1SchemaJson from "../schemas/schedule1-parse-result.v1.schema.json" with { type: "json" };
import Schedule1ExciseLeviesParseResultV1SchemaJson from "../schemas/schedule1-excise-levies-parse-result.v1.schema.json" with { type: "json" };
import Schedule2ParseResultV1SchemaJson from "../schemas/schedule2-parse-result.v1.schema.json" with { type: "json" };
import Schedule3ParseResultV1SchemaJson from "../schemas/schedule3-parse-result.v1.schema.json" with { type: "json" };
import Schedule4ParseResultV1SchemaJson from "../schemas/schedule4-parse-result.v1.schema.json" with { type: "json" };
import Schedule5ParseResultV1SchemaJson from "../schemas/schedule5-parse-result.v1.schema.json" with { type: "json" };
import Schedule6ParseResultV1SchemaJson from "../schemas/schedule6-parse-result.v1.schema.json" with { type: "json" };
import Schedule1QaReportV1SchemaJson from "../schemas/schedule1-qa-report.v1.schema.json" with { type: "json" };
import ScheduleFamilyQaReportV1SchemaJson from "../schemas/schedule-family-qa-report.v1.schema.json" with { type: "json" };
import TariffLineV1SchemaJson from "../schemas/tariff-line.v1.schema.json" with { type: "json" };

export const CustomsDutyEstimateV1Schema = CustomsDutyEstimateV1SchemaJson;
export const CustomsRulesetContainerV1Schema = CustomsRulesetContainerV1SchemaJson;
export const CustomsRulesetV1Schema = CustomsRulesetV1SchemaJson;
export const Schedule1ParseResultV1Schema = Schedule1ParseResultV1SchemaJson;
export const Schedule1ExciseLeviesParseResultV1Schema = Schedule1ExciseLeviesParseResultV1SchemaJson;
export const Schedule2ParseResultV1Schema = Schedule2ParseResultV1SchemaJson;
export const Schedule3ParseResultV1Schema = Schedule3ParseResultV1SchemaJson;
export const Schedule4ParseResultV1Schema = Schedule4ParseResultV1SchemaJson;
export const Schedule5ParseResultV1Schema = Schedule5ParseResultV1SchemaJson;
export const Schedule6ParseResultV1Schema = Schedule6ParseResultV1SchemaJson;
export const Schedule1QaReportV1Schema = Schedule1QaReportV1SchemaJson;
export const ScheduleFamilyQaReportV1Schema = ScheduleFamilyQaReportV1SchemaJson;
export const TariffLineV1Schema = TariffLineV1SchemaJson;
